/**
 * News Demo Data — Données réalistes de news économiques pour le mode démo
 * Couvre : macro, forex, crypto, indices, énergie, banques centrales, géopolitique
 */

import type { NewsItem, NewsDaySummary, HistoricalReaction } from './newsEngine';
import { calculateImpactScore, getAffectedAssets } from './newsEngine';

// ─── Helper ──────────────────────────────────────────────
function makeNews(p: Omit<NewsItem, 'id' | 'createdAt' | 'impactScore'> & Partial<Pick<NewsItem, 'id'>>): NewsItem {
  const item: NewsItem = {
    ...p,
    id: p.id || `news-${p.timestamp}-${Math.random().toString(36).slice(2, 6)}`,
    createdAt: Date.now(),
    impactScore: 0,
  };
  item.impactScore = calculateImpactScore(item);
  return item;
}

// ─── TODAY'S NEWS (June 7, 2026) ────────────────────────

export const DEMO_NEWS: NewsItem[] = [
  // ─── CRITICAL ──────────────────────────────────────────
  makeNews({
    id: 'news-001',
    timestamp: Date.now() + 3600000,
    timeLabel: '14:30',
    country: 'États-Unis',
    currency: 'USD',
    category: 'macro',
    title: 'Non-Farm Payrolls (NFP) Mai 2026',
    source: 'Bureau of Labor Statistics',
    impact: 'critical',
    status: 'upcoming',
    previousValue: '185K',
    forecastValue: '175K',
    actualValue: null,
    surprise: null,
    affectedAssets: getAffectedAssets('USD', 'macro'),
    probableDirection: null,
    aiDecision: 'NO_TRADE',
    riskLevel: 'high',
    signalNote: 'D',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: '/xauusd',
      institutionalAnalysis: '/institutional-comparator',
      decisionCenter: '/decision-center',
      affectedAsset: '/xauusd',
      createAlert: '/alerts',
      externalSource: 'https://www.bls.gov',
    },
    whyImportant: 'Le NFP est l\'indicateur d\'emploi le plus important des USA. Il influence directement les décisions de la Fed sur les taux d\'intérêt. Un résultat supérieur aux attentes renforce le dollar et met la pression sur l\'or et les indices.',
    marketReaction: 'Volatilité attendue de 50-100 pips sur EUR/USD, 20-40$ sur XAU/USD, 1-2% sur NASDAQ dans les 5 minutes suivant la publication.',
    beforeSignal: 'XAU/USD en consolidation latérale avant la news',
    afterSignal: 'Suspension des signaux — attente de réaction',
    invalidationLevel: 'Break sous 3365$ ou au-dessus de 3400$ invalide le range',
  }),

  makeNews({
    id: 'news-002',
    timestamp: Date.now() - 7200000,
    timeLabel: '08:30',
    country: 'États-Unis',
    currency: 'USD',
    category: 'macro',
    title: 'Taux de chômage (Employment Rate) Mai',
    source: 'Bureau of Labor Statistics',
    impact: 'critical',
    status: 'past',
    previousValue: '3.9%',
    forecastValue: '3.8%',
    actualValue: '4.1%',
    surprise: 'negative',
    affectedAssets: getAffectedAssets('USD', 'macro'),
    probableDirection: 'bearish',
    aiDecision: 'ATTENDRE',
    riskLevel: 'medium',
    signalNote: 'C',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: '/institutional-comparator',
      decisionCenter: '/decision-center',
      affectedAsset: '/xauusd',
      createAlert: '/alerts',
      externalSource: 'https://www.bls.gov',
    },
    whyImportant: 'Hausse du chômage au-dessus des attentes = économie qui ralentit. Cela renforce les attentes de baisse des taux Fed (dovish) — bullish pour l\'or et les indices, bearish pour le dollar.',
    marketReaction: 'XAU/USD +15$ dans les 15 minutes, EUR/USD +40 pips, NASDAQ +0.8%, DXY -0.35%.',
    beforeSignal: 'EUR/USD signal d\'achat H1',
    afterSignal: 'Achat confirmé — momentum haussier post-news',
    invalidationLevel: 'Retour sous 1.0820',
  }),

  // ─── HIGH IMPACT ───────────────────────────────────────
  makeNews({
    id: 'news-003',
    timestamp: Date.now() + 18000000,
    timeLabel: '18:00',
    country: 'États-Unis',
    currency: 'USD',
    category: 'central_bank',
    title: 'Discours Jerome Powell (Fed Chair)',
    source: 'Federal Reserve',
    impact: 'high',
    status: 'upcoming',
    previousValue: '—',
    forecastValue: '—',
    actualValue: null,
    surprise: null,
    affectedAssets: getAffectedAssets('USD', 'central_bank'),
    probableDirection: null,
    aiDecision: 'NO_TRADE',
    riskLevel: 'high',
    signalNote: 'C',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: '/institutional-comparator',
      decisionCenter: '/decision-center',
      affectedAsset: '/xauusd',
      createAlert: '/alerts',
      externalSource: 'https://www.federalreserve.gov',
    },
    whyImportant: 'Tout discours de Powell peut modifier les attentes de marché sur les taux. Les marchés réagissent aux nuances sur l\'inflation, l\'emploi et la trajectoire future des taux.',
    marketReaction: 'Volatilité typique : 30-80 pips forex, 10-25$ XAU/USD. Attention aux annonces imprévues.',
    beforeSignal: 'Marchés en attente — range pré-Powell',
    afterSignal: 'À déterminer',
    invalidationLevel: 'Breakout du range H4',
  }),

  makeNews({
    id: 'news-004',
    timestamp: Date.now() - 3600000,
    timeLabel: '11:00',
    country: 'Zone Euro',
    currency: 'EUR',
    category: 'macro',
    title: 'PIB Zone Euro T1 2026 (révision)',
    source: 'Eurostat',
    impact: 'high',
    status: 'past',
    previousValue: '0.1%',
    forecastValue: '0.2%',
    actualValue: '0.3%',
    surprise: 'positive',
    affectedAssets: getAffectedAssets('EUR', 'macro'),
    probableDirection: 'bullish',
    aiDecision: 'ACHETER',
    riskLevel: 'low',
    signalNote: 'B',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: '/decision-center',
      affectedAsset: null,
      createAlert: null,
      externalSource: 'https://ec.europa.eu/eurostat',
    },
    whyImportant: 'Révision positive du PIB = économie européenne plus résiliente que prévu. Cela réduit la pression sur la BCE pour baisser les taux rapidement — bullish pour l\'euro.',
    marketReaction: 'EUR/USD +25 pips, DE40 +0.5%.',
    beforeSignal: 'EUR/USD neutre',
    afterSignal: 'Achat confirmé sur H1',
    invalidationLevel: 'Retour sous 1.0800',
  }),

  makeNews({
    id: 'news-005',
    timestamp: Date.now() - 10800000,
    timeLabel: '09:00',
    country: 'Allemagne',
    currency: 'EUR',
    category: 'macro',
    title: 'Production Industrielle Allemagne Avril',
    source: 'Destatis',
    impact: 'high',
    status: 'past',
    previousValue: '-0.4%',
    forecastValue: '0.2%',
    actualValue: '-0.1%',
    surprise: 'negative',
    affectedAssets: ['EUR/USD', 'DE40', 'EUR/JPY', 'EUR/GBP'],
    probableDirection: 'bearish',
    aiDecision: 'ATTENDRE',
    riskLevel: 'medium',
    signalNote: 'C',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: '/decision-center',
      affectedAsset: null,
      createAlert: null,
      externalSource: 'https://www.destatis.de',
    },
    whyImportant: 'La production industrielle allemande reste faible. Signe que la reprise économique est hésitante — baissier pour l\'euro et le DAX.',
    marketReaction: 'DE40 -0.3%, EUR/USD -15 pips.',
    beforeSignal: 'DE40 en tendance haussière H4',
    afterSignal: 'Signal suspendu — risque de correction',
    invalidationLevel: 'Perte de 18500',
  }),

  // ─── MEDIUM IMPACT ─────────────────────────────────────
  makeNews({
    id: 'news-006',
    timestamp: Date.now() - 1800000,
    timeLabel: '12:30',
    country: 'États-Unis',
    currency: 'USD',
    category: 'macro',
    title: 'Demande initiales d\'allocations chômage (Weekly Claims)',
    source: 'Department of Labor',
    impact: 'medium',
    status: 'past',
    previousValue: '215K',
    forecastValue: '218K',
    actualValue: '222K',
    surprise: 'negative',
    affectedAssets: ['USD/JPY', 'XAU/USD', 'NAS100', 'DXY'],
    probableDirection: 'bearish',
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: 'B',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Légère hausse des demandes de chômage. Signe que le marché du travail commence à se détendre — modérément dovish pour la Fed.',
    marketReaction: 'Faible impact, XAU/USD +3$, DXY -0.1%',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-007',
    timestamp: Date.now() - 5400000,
    timeLabel: '10:00',
    country: 'Royaume-Uni',
    currency: 'GBP',
    category: 'macro',
    title: 'Halifax House Prices (House Price Index) Mai',
    source: 'Halifax',
    impact: 'medium',
    status: 'past',
    previousValue: '-0.1%',
    forecastValue: '0.3%',
    actualValue: '0.2%',
    surprise: 'neutral',
    affectedAssets: ['GBP/USD', 'EUR/GBP', 'UK100'],
    probableDirection: 'neutral',
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Les prix immobiliers britanniques en légère hausse = stabilité économique. Impact modéré sur la livre sterling.',
    marketReaction: 'GBP/USD stable, +5 pips.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-008',
    timestamp: Date.now() + 7200000,
    timeLabel: '15:00',
    country: 'États-Unis',
    currency: 'USD',
    category: 'macro',
    title: 'ISM Services PMI Mai',
    source: 'Institute for Supply Management',
    impact: 'high',
    status: 'upcoming',
    previousValue: '49.4',
    forecastValue: '50.2',
    actualValue: null,
    surprise: null,
    affectedAssets: ['USD/JPY', 'XAU/USD', 'NAS100', 'SPX500', 'EUR/USD'],
    probableDirection: null,
    aiDecision: 'ATTENDRE',
    riskLevel: 'medium',
    signalNote: null,
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: '/alerts',
      externalSource: null,
    },
    whyImportant: 'Le secteur des services représente ~80% de l\'économie US. Un PMI au-dessus de 50 = expansion. Impact significatif sur le dollar et les indices.',
    marketReaction: 'Attendu : 30-60 pips sur forex, 0.5-1% sur indices.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  // ─── CRYPTO NEWS ───────────────────────────────────────
  makeNews({
    id: 'news-009',
    timestamp: Date.now() - 900000,
    timeLabel: '13:00',
    country: 'États-Unis',
    currency: 'USD',
    category: 'crypto',
    title: 'SEC approuve 3 nouveaux ETFs Ethereum spot',
    source: 'SEC',
    impact: 'high',
    status: 'past',
    previousValue: '—',
    forecastValue: '—',
    actualValue: 'Approuvé',
    surprise: 'positive',
    affectedAssets: ['ETH/USD', 'BTC/USD', 'SOL/USD', 'BNB/USD'],
    probableDirection: 'bullish',
    aiDecision: 'ACHETER',
    riskLevel: 'medium',
    signalNote: 'A',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: '/decision-center',
      affectedAsset: null,
      createAlert: '/alerts',
      externalSource: 'https://www.sec.gov',
    },
    whyImportant: 'Approbation ETF Ethereum = adoption institutionnelle massive. Historiquement bullish pour ETH (+10-20% dans les jours suivants) et pour tout le marché crypto.',
    marketReaction: 'ETH/USD +8.5% en 30 minutes, BTC/USD +3.2%, SOL/USD +12%. Volume x5.',
    beforeSignal: 'ETH en consolidation',
    afterSignal: 'Achat fort — breakout confirmé',
    invalidationLevel: 'Retour sous 3650$',
  }),

  makeNews({
    id: 'news-010',
    timestamp: Date.now() + 14400000,
    timeLabel: '17:00',
    country: 'Global',
    currency: 'USD',
    category: 'crypto',
    title: 'Bitcoin : Mise à jour réseau (Taproot v2) activation',
    source: 'Bitcoin Core',
    impact: 'medium',
    status: 'upcoming',
    previousValue: '—',
    forecastValue: '—',
    actualValue: null,
    surprise: null,
    affectedAssets: ['BTC/USD', 'ETH/USD'],
    probableDirection: null,
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Mise à jour technique du réseau Bitcoin. Généralement neutre à légèrement positive si sans problème technique.',
    marketReaction: 'Impact attendu : faible à modéré.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  // ─── ENERGY NEWS ───────────────────────────────────────
  makeNews({
    id: 'news-011',
    timestamp: Date.now() - 4500000,
    timeLabel: '10:30',
    country: 'États-Unis',
    currency: 'USD',
    category: 'energy',
    title: 'Inventaires de pétrole brut EIA (Weekly)',
    source: 'EIA',
    impact: 'high',
    status: 'past',
    previousValue: '+1.8M',
    forecastValue: '-0.5M',
    actualValue: '-2.3M',
    surprise: 'positive',
    affectedAssets: ['WTI', 'BRENT', 'USD/CAD', 'NATGAS'],
    probableDirection: 'bullish',
    aiDecision: 'ACHETER',
    riskLevel: 'low',
    signalNote: 'B',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: '/alerts',
      externalSource: 'https://www.eia.gov',
    },
    whyImportant: 'Baisse des stocks de pétrole bien plus forte que prévu = demande robuste. Très bullish pour le pétrole.',
    marketReaction: 'WTI +2.8%, BRENT +2.5% dans les 15 minutes. USD/CAD -0.3%.',
    beforeSignal: 'WTI en tendance haussière H4',
    afterSignal: 'Achat confirmé — momentum fort',
    invalidationLevel: 'Retour sous 77$',
  }),

  // ─── GEOPOLITICAL ──────────────────────────────────────
  makeNews({
    id: 'news-012',
    timestamp: Date.now() - 600000,
    timeLabel: '13:30',
    country: 'Moyen-Orient',
    currency: 'USD',
    category: 'geopolitics',
    title: 'Escalade géopolitique — tensions dans le Golfe Persique',
    source: 'Reuters',
    impact: 'critical',
    status: 'live',
    previousValue: '—',
    forecastValue: '—',
    actualValue: 'Tensions en hausse',
    surprise: 'negative',
    affectedAssets: ['XAU/USD', 'WTI', 'BRENT', 'USD/JPY', 'BTC/USD'],
    probableDirection: 'bullish',
    aiDecision: 'NO_TRADE',
    riskLevel: 'high',
    signalNote: 'C',
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: '/xauusd',
      institutionalAnalysis: null,
      decisionCenter: '/decision-center',
      affectedAsset: '/xauusd',
      createAlert: '/alerts',
      externalSource: 'https://www.reuters.com',
    },
    whyImportant: 'Tensions géopolitiques = flux vers les actifs refuge (or, obligations US, yen). Risque de spike volatilité sur le pétrole si le Golfe est affecté.',
    marketReaction: 'XAU/USD +12$ instantanément, WTI +1.5%, USD/JPY -30 pips. VIX +8%.',
    beforeSignal: 'XAU/USD consolidation',
    afterSignal: 'Volatilité extrême — No Trade',
    invalidationLevel: 'Attendre stabilisation 15-30 min',
  }),

  // ─── EARNINGS ──────────────────────────────────────────
  makeNews({
    id: 'news-013',
    timestamp: Date.now() - 7200000,
    timeLabel: '12:00',
    country: 'États-Unis',
    currency: 'USD',
    category: 'earnings',
    title: 'NVIDIA Q1 FY2027 — Résultats trimestriels',
    source: 'NVIDIA Corp',
    impact: 'high',
    status: 'past',
    previousValue: '$5.98 EPS',
    forecastValue: '$6.25 EPS',
    actualValue: '$6.85 EPS',
    surprise: 'positive',
    affectedAssets: ['NVDA', 'NAS100', 'SPX500', 'AMD'],
    probableDirection: 'bullish',
    aiDecision: 'ACHETER',
    riskLevel: 'low',
    signalNote: 'A',
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: 'https://investor.nvidia.com',
    },
    whyImportant: 'NVIDIA bat largement les attentes avec guidance haussière. Impact fort sur le NASDAQ et le secteur des semi-conducteurs.',
    marketReaction: 'NVDA +8.2% after-hours, NAS100 futures +1.2%, AMD +4.5%.',
    beforeSignal: 'NVDA en accumulation',
    afterSignal: 'Achat confirmé — breakout earnings',
    invalidationLevel: 'Perte de 148$',
  }),

  // ─── FED SPEAK ─────────────────────────────────────────
  makeNews({
    id: 'news-014',
    timestamp: Date.now() + 9000000,
    timeLabel: '19:30',
    country: 'États-Unis',
    currency: 'USD',
    category: 'central_bank',
    title: 'FOMC Minutes — Compte-rendu de la réunion',
    source: 'Federal Reserve',
    impact: 'high',
    status: 'upcoming',
    previousValue: '—',
    forecastValue: '—',
    actualValue: null,
    surprise: null,
    affectedAssets: getAffectedAssets('USD', 'central_bank'),
    probableDirection: null,
    aiDecision: 'NO_TRADE',
    riskLevel: 'high',
    signalNote: null,
    links: {
      technicalAnalysis: '/technical',
      fundamentalAnalysis: null,
      institutionalAnalysis: '/institutional-comparator',
      decisionCenter: '/decision-center',
      affectedAsset: '/xauusd',
      createAlert: '/alerts',
      externalSource: 'https://www.federalreserve.gov',
    },
    whyImportant: 'Les minutes FOMC révèlent les débats internes de la Fed. Toute mention de "patient" ou "prudent" est analysée mot par mot par les marchés.',
    marketReaction: 'Volatilité typique : 40-90 pips forex, 15-30$ XAU/USD.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  // ─── MORE MEDIUM/LOW ───────────────────────────────────
  makeNews({
    id: 'news-015',
    timestamp: Date.now() - 2700000,
    timeLabel: '11:30',
    country: 'Canada',
    currency: 'CAD',
    category: 'macro',
    title: 'Ivey PMI Canada Mai',
    source: 'Richard Ivey School of Business',
    impact: 'medium',
    status: 'past',
    previousValue: '53.4',
    forecastValue: '54.0',
    actualValue: '53.8',
    surprise: 'neutral',
    affectedAssets: ['USD/CAD', 'CAD/JPY', 'WTI'],
    probableDirection: 'neutral',
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'PMI canadien légèrement en-deçà mais reste expansionniste. Impact modéré sur CAD.',
    marketReaction: 'USD/CAD stable.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-016',
    timestamp: Date.now() - 14400000,
    timeLabel: '07:00',
    country: 'Japon',
    currency: 'JPY',
    category: 'central_bank',
    title: 'Discours gouverneur BoJ Ueda',
    source: 'Bank of Japan',
    impact: 'medium',
    status: 'past',
    previousValue: '—',
    forecastValue: '—',
    actualValue: 'Hawkish tone',
    surprise: 'positive',
    affectedAssets: ['USD/JPY', 'EUR/JPY', 'GBP/JPY', 'JP225'],
    probableDirection: 'bearish',
    aiDecision: 'ATTENDRE',
    riskLevel: 'medium',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Ton plus hawkish de la BoJ = possible hausse de taux japonais. Renforce le yen — bearish pour USD/JPY.',
    marketReaction: 'USD/JPY -45 pips, JP225 -0.6%.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-017',
    timestamp: Date.now() + 10800000,
    timeLabel: '16:00',
    country: 'États-Unis',
    currency: 'USD',
    category: 'bonds',
    title: 'Ventes obligations 10Y (Treasury Auction)',
    source: 'US Treasury',
    impact: 'medium',
    status: 'upcoming',
    previousValue: '4.18% yield',
    forecastValue: '4.25% yield',
    actualValue: null,
    surprise: null,
    affectedAssets: ['US10Y', 'US2Y', 'XAU/USD', 'EUR/USD', 'DXY'],
    probableDirection: null,
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Une demande faible aux enchères Treasury = hausse des rendements — bearish pour l\'or et les indices.',
    marketReaction: 'Impact modéré attendu.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-018',
    timestamp: Date.now() - 18000000,
    timeLabel: '06:00',
    country: 'Chine',
    currency: 'CNY',
    category: 'macro',
    title: 'Balance commerciale Chine Mai',
    source: 'General Administration of Customs',
    impact: 'medium',
    status: 'past',
    previousValue: '$72.3B',
    forecastValue: '$78.0B',
    actualValue: '$81.2B',
    surprise: 'positive',
    affectedAssets: ['AUD/USD', 'COPPER', 'WTI', 'JP225', 'XAU/USD'],
    probableDirection: 'bullish',
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Excédent commercial chinois supérieur aux attentes = demande mondiale robuste. Bullish pour les matières premières et AUD.',
    marketReaction: 'AUD/USD +20 pips, COPPER +0.8%.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  // ─── REGULATION ────────────────────────────────────────
  makeNews({
    id: 'news-019',
    timestamp: Date.now() - 12600000,
    timeLabel: '08:00',
    country: 'États-Unis',
    currency: 'USD',
    category: 'regulation',
    title: 'MiCA Phase 2 — Régulation stablecoins EU en vigueur',
    source: 'European Commission',
    impact: 'medium',
    status: 'past',
    previousValue: '—',
    forecastValue: '—',
    actualValue: 'En vigueur',
    surprise: 'neutral',
    affectedAssets: ['BTC/USD', 'ETH/USD', 'BNB/USD'],
    probableDirection: 'neutral',
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Nouvelles règles MiCA sur les stablecoins en Europe. Impact neutre à long terme mais monitoring nécessaire.',
    marketReaction: 'Faible impact immédiat.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  // ─── LOW IMPACT ────────────────────────────────────────
  makeNews({
    id: 'news-020',
    timestamp: Date.now() - 9000000,
    timeLabel: '07:30',
    country: 'France',
    currency: 'EUR',
    category: 'macro',
    title: 'Balance commerciale France Avril',
    source: 'Douanes Françaises',
    impact: 'low',
    status: 'past',
    previousValue: '-6.2B',
    forecastValue: '-5.8B',
    actualValue: '-6.0B',
    surprise: 'neutral',
    affectedAssets: ['EUR/USD', 'FR40'],
    probableDirection: 'neutral',
    aiDecision: null,
    riskLevel: null,
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Déficit commercial français stable. Impact limité sur les marchés.',
    marketReaction: 'Aucun impact significatif.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-021',
    timestamp: Date.now() + 5400000,
    timeLabel: '15:30',
    country: 'États-Unis',
    currency: 'USD',
    category: 'macro',
    title: 'Factory Orders Avril',
    source: 'US Census Bureau',
    impact: 'low',
    status: 'upcoming',
    previousValue: '0.4%',
    forecastValue: '0.3%',
    actualValue: null,
    surprise: null,
    affectedAssets: ['USD/JPY', 'NAS100'],
    probableDirection: null,
    aiDecision: null,
    riskLevel: null,
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Secondaire. Impact faible sauf surprise majeure.',
    marketReaction: null,
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-022',
    timestamp: Date.now() - 10800000,
    timeLabel: '09:30',
    country: 'Royaume-Uni',
    currency: 'GBP',
    category: 'central_bank',
    title: 'Discours MPC member Mann',
    source: 'Bank of England',
    impact: 'low',
    status: 'past',
    previousValue: '—',
    forecastValue: '—',
    actualValue: 'Dovish',
    surprise: 'negative',
    affectedAssets: ['GBP/USD', 'EUR/GBP'],
    probableDirection: 'bearish',
    aiDecision: 'ATTENDRE',
    riskLevel: 'low',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Membre MPC dovish = possible baisse de taux BoE plus tôt. Légèrement bearish GBP.',
    marketReaction: 'GBP/USD -10 pips.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-023',
    timestamp: Date.now() + 21600000,
    timeLabel: '21:00',
    country: 'Nouvelle-Zélande',
    currency: 'NZD',
    category: 'macro',
    title: 'Décision taux d\'intérêt RBNZ',
    source: 'Reserve Bank of New Zealand',
    impact: 'high',
    status: 'upcoming',
    previousValue: '5.50%',
    forecastValue: '5.25%',
    actualValue: null,
    surprise: null,
    affectedAssets: ['NZD/USD', 'AUD/USD', 'AUD/NZD', 'JP225'],
    probableDirection: null,
    aiDecision: 'NO_TRADE',
    riskLevel: 'high',
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: '/alerts',
      externalSource: null,
    },
    whyImportant: 'Possible première baisse de taux RBNZ. Impact significatif sur NZD et AUD par corrélation.',
    marketReaction: 'Attendu : 40-80 pips sur NZD/USD.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-024',
    timestamp: Date.now() - 21600000,
    timeLabel: '05:00',
    country: 'Australie',
    currency: 'AUD',
    category: 'macro',
    title: 'Trade Balance Australie Avril',
    source: 'ABS',
    impact: 'low',
    status: 'past',
    previousValue: '+5.2B',
    forecastValue: '+5.5B',
    actualValue: '+5.8B',
    surprise: 'positive',
    affectedAssets: ['AUD/USD', 'AUD/JPY'],
    probableDirection: 'bullish',
    aiDecision: null,
    riskLevel: null,
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Excédent commercial australien en hausse. Léger soutien pour AUD.',
    marketReaction: 'AUD/USD +8 pips.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),

  makeNews({
    id: 'news-025',
    timestamp: Date.now() - 300000,
    timeLabel: '14:00',
    country: 'États-Unis',
    currency: 'USD',
    category: 'stocks',
    title: 'Apple (AAPL) annonce partenariat IA majeur avec OpenAI',
    source: 'Apple Inc.',
    impact: 'high',
    status: 'live',
    previousValue: '—',
    forecastValue: '—',
    actualValue: 'Annoncé',
    surprise: 'positive',
    affectedAssets: ['AAPL', 'NAS100', 'SPX500', 'MSFT', 'GOOGL', 'META'],
    probableDirection: 'bullish',
    aiDecision: 'ACHETER',
    riskLevel: 'medium',
    signalNote: 'A',
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: '/alerts',
      externalSource: null,
    },
    whyImportant: 'Partenariat IA Apple-OpenAI = compétition directe avec Microsoft/Google. Impact majeur sur le secteur tech et le NASDAQ.',
    marketReaction: 'AAPL +4.2% pre-market, NAS100 futures +0.8%, MSFT -1.2% (concurrence), GOOGL -0.8%.',
    beforeSignal: 'AAPL en range',
    afterSignal: 'Achat — breakout sur news',
    invalidationLevel: 'Retour sous 235$',
  }),

  makeNews({
    id: 'news-026',
    timestamp: Date.now() - 16200000,
    timeLabel: '06:30',
    country: 'Suisse',
    currency: 'CHF',
    category: 'macro',
    title: 'Indice KOF Suisse Leading Indicator Mai',
    source: 'KOF Swiss Economic Institute',
    impact: 'low',
    status: 'past',
    previousValue: '98.2',
    forecastValue: '99.0',
    actualValue: '98.8',
    surprise: 'neutral',
    affectedAssets: ['USD/CHF', 'EUR/CHF'],
    probableDirection: 'neutral',
    aiDecision: null,
    riskLevel: null,
    signalNote: null,
    links: {
      technicalAnalysis: null,
      fundamentalAnalysis: null,
      institutionalAnalysis: null,
      decisionCenter: null,
      affectedAsset: null,
      createAlert: null,
      externalSource: null,
    },
    whyImportant: 'Indicateur avancé suisse stable. Impact faible sur CHF.',
    marketReaction: 'Aucun mouvement significatif.',
    beforeSignal: null,
    afterSignal: null,
    invalidationLevel: null,
  }),
];

// ─── HISTORICAL REACTIONS ───────────────────────────────

export const DEMO_NEWS_HISTORY: HistoricalReaction[] = [
  {
    newsId: 'hist-001',
    title: 'NFP Avril 2026',
    category: 'macro',
    impact: 'critical',
    actualValue: '142K',
    forecastValue: '185K',
    surprise: 'negative',
    xauReaction: '+28$ (0.8%)',
    eurUsdReaction: '+65 pips (0.6%)',
    nasdaqReaction: '+1.2%',
    btcReaction: '+2.1%',
    volatility5m: 'Élevée (2.3%)',
    volatility15m: 'Modérée (1.1%)',
    volatility1h: 'Normale (0.4%)',
    beforeDecision: 'No Trade',
    afterDecision: 'Achat XAU/USD confirmé',
    result: 'Gagnant — +28$',
    lesson: 'NFP faible = dovish Fed = bullish or. Attendre 5 min post-news pour entrer.',
  },
  {
    newsId: 'hist-002',
    title: 'CPI USA Mars 2026',
    category: 'macro',
    impact: 'critical',
    actualValue: '3.5%',
    forecastValue: '3.2%',
    surprise: 'negative',
    xauReaction: '-22$ (-0.7%)',
    eurUsdReaction: '-85 pips (-0.8%)',
    nasdaqReaction: '-1.8%',
    btcReaction: '-3.5%',
    volatility5m: 'Très élevée (3.1%)',
    volatility15m: 'Élevée (1.8%)',
    volatility1h: 'Modérée (0.9%)',
    beforeDecision: 'No Trade',
    afterDecision: 'Attendre',
    result: 'Neutre — pas d\'entrée',
    lesson: 'CPI fort = hawkish Fed = bearish or et indices. No Trade jusqu\'à stabilisation.',
  },
  {
    newsId: 'hist-003',
    title: 'Décision FOMC Mars 2026',
    category: 'central_bank',
    impact: 'critical',
    actualValue: 'Taux maintenus 5.25-5.50%',
    forecastValue: '—',
    surprise: 'neutral',
    xauReaction: '+8$ (0.2%)',
    eurUsdReaction: '+20 pips (0.2%)',
    nasdaqReaction: '+0.5%',
    btcReaction: '+1.2%',
    volatility5m: 'Élevée (1.8%)',
    volatility15m: 'Modérée (0.6%)',
    volatility1h: 'Normale (0.3%)',
    beforeDecision: 'No Trade',
    afterDecision: 'Achat modéré XAU/USD',
    result: 'Gagnant — +8$',
    lesson: 'Maintien des taux = patience Fed = léger soutien aux actifs risqués.',
  },
  {
    newsId: 'hist-004',
    title: 'Approbation ETF Bitcoin Jan 2024 (ref)',
    category: 'crypto',
    impact: 'critical',
    actualValue: 'Approuvé',
    forecastValue: '—',
    surprise: 'positive',
    xauReaction: '-5$ (-0.2%)',
    eurUsdReaction: 'Stable',
    nasdaqReaction: '+0.3%',
    btcReaction: '+18.5%',
    volatility5m: 'Extrême (8.2%)',
    volatility15m: 'Très élevée (5.1%)',
    volatility1h: 'Élevée (3.2%)',
    beforeDecision: 'Attendre',
    afterDecision: 'Achat BTC',
    result: 'Gagnant — +18.5%',
    lesson: 'Approbation ETF crypto = catalyseur structurel. Entrer sur retest post-spike.',
  },
];
